# Generated by Django 3.0.2 on 2020-02-10 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5)),
                ('turno', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.CharField(max_length=11)),
                ('martes', models.CharField(max_length=11)),
                ('miercoles', models.CharField(max_length=11)),
                ('jueves', models.CharField(max_length=11)),
                ('viernes', models.CharField(max_length=11)),
                ('sabado', models.CharField(max_length=11)),
                ('domingo', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoMateria',
            fields=[
                ('inscritos', models.PositiveSmallIntegerField()),
                ('horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Grupo.Horario')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupo.Grupo')),
            ],
        ),
    ]
