# Generated by Django 3.0.2 on 2020-02-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Materia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5)),
                ('turno', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscritos', models.PositiveSmallIntegerField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupo.Grupo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Materia.Materia')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='materia',
            field=models.ManyToManyField(through='Grupo.GrupoMateria', to='Materia.Materia'),
        ),
    ]
