# Generated by Django 3.0.2 on 2020-02-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_parcial', models.PositiveSmallIntegerField()),
                ('segundo_parcial', models.PositiveSmallIntegerField()),
                ('tercer_parcial', models.PositiveSmallIntegerField()),
                ('final', models.PositiveSmallIntegerField()),
                ('extraordinario', models.PositiveSmallIntegerField(null=True)),
                ('ets', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('creditos', models.DecimalField(decimal_places=2, max_digits=2)),
                ('nivel', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaInscrita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('fecha_inscrita', models.DateTimeField(auto_now_add=True)),
                ('aprobada', models.BooleanField(null=True)),
            ],
        ),
    ]
