# Generated by Django 3.0.2 on 2020-02-10 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Materia', '0001_initial'),
        ('Persona', '0001_initial'),
        ('Grupo', '0002_auto_20200210_1842'),
        ('Departamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiainscrita',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.Alumno'),
        ),
        migrations.AddField(
            model_name='materiainscrita',
            name='grupo_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupo.GrupoMateria'),
        ),
        migrations.AddField(
            model_name='materia',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamento.Departamento'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Materia.MateriaInscrita'),
        ),
    ]
