# Generated by Django 3.0.3 on 2020-02-10 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Materia', '0002_materiainscrita'),
        ('Grupo', '0002_horario'),
        ('Persona', '0003_auto_20200210_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiainscrita',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.Alumno'),
        ),
        migrations.AddField(
            model_name='materiainscrita',
            name='grupo_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupo.GrupoMateria'),
        ),
    ]
