# Generated by Django 3.0.2 on 2020-02-10 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Materia', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('Grupo', '0002_auto_20200210_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('curp', models.CharField(max_length=18)),
                ('fecha_de_nacimiento', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('datos_personales', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Persona.Persona')),
                ('boleta', models.CharField(max_length=10)),
                ('materia_inscrita', models.ManyToManyField(through='Materia.MateriaInscrita', to='Grupo.GrupoMateria')),
            ],
        ),
    ]
