# Generated by Django 3.0.3 on 2020-02-10 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Materia', '0002_materiainscrita'),
        ('Grupo', '0002_horario'),
        ('Persona', '0002_persona_materia_inscrita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='materia_inscrita',
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('datos_personales', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Persona.Persona')),
                ('boleta', models.CharField(max_length=10)),
                ('materia_inscrita', models.ManyToManyField(through='Materia.MateriaInscrita', to='Grupo.GrupoMateria')),
            ],
        ),
    ]
